"""add pg_trgm extension

Revision ID: 09dbf3ca3bd5
Revises: 1fdf6058069f
Create Date: 2022-12-19 14:01:05.406979

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "09dbf3ca3bd5"
down_revision = "1fdf6058069f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(sa.text("CREATE EXTENSION IF NOT EXISTS pg_trgm;"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(sa.text("DROP EXTENSION pg_trgm;"))
    # ### end Alembic commands ###
