"""update tables for image support

Revision ID: 1fdf6058069f
Revises: 6080f8260a0f
Create Date: 2022-11-22 23:22:55.157459

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1fdf6058069f"
down_revision = "6080f8260a0f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("campaigns", sa.Column("cover_id", sa.Integer(), nullable=True))
    op.drop_constraint("campaigns_cover_fkey", "campaigns", type_="foreignkey")
    op.create_foreign_key(
        None, "campaigns", "images", ["cover_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_column("campaigns", "cover")
    op.add_column("milestones", sa.Column("picture_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        None, "milestones", "images", ["picture_id"], ["id"], ondelete="CASCADE"
    )
    op.add_column("rewards", sa.Column("picture_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        None, "rewards", "images", ["picture_id"], ["id"], ondelete="CASCADE"
    )
    op.add_column("updates", sa.Column("picture_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        None, "updates", "images", ["picture_id"], ["id"], ondelete="CASCADE"
    )
    op.add_column("users", sa.Column("portrait_id", sa.Integer(), nullable=True))
    op.drop_constraint("users_portrait_fkey", "users", type_="foreignkey")
    op.create_foreign_key(
        None, "users", "images", ["portrait_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_column("users", "portrait")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("portrait", sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.drop_constraint(None, "users", type_="foreignkey")
    op.create_foreign_key(
        "users_portrait_fkey",
        "users",
        "images",
        ["portrait"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("users", "portrait_id")
    op.drop_constraint(None, "updates", type_="foreignkey")
    op.drop_column("updates", "picture_id")
    op.drop_constraint(None, "rewards", type_="foreignkey")
    op.drop_column("rewards", "picture_id")
    op.drop_constraint(None, "milestones", type_="foreignkey")
    op.drop_column("milestones", "picture_id")
    op.add_column(
        "campaigns",
        sa.Column("cover", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "campaigns", type_="foreignkey")
    op.create_foreign_key(
        "campaigns_cover_fkey",
        "campaigns",
        "images",
        ["cover"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("campaigns", "cover_id")
    # ### end Alembic commands ###
