"""add image fields

Revision ID: 6080f8260a0f
Revises: 79a6909c612a
Create Date: 2022-11-22 21:24:33.368853

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "6080f8260a0f"
down_revision = "79a6909c612a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("campaigns", sa.Column("cover", sa.Integer(), nullable=True))
    op.create_foreign_key(
        None, "campaigns", "images", ["cover"], ["id"], ondelete="CASCADE"
    )
    op.add_column("users", sa.Column("portrait", sa.Integer(), nullable=True))
    op.create_foreign_key(
        None, "users", "images", ["portrait"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="foreignkey")
    op.drop_column("users", "portrait")
    op.drop_constraint(None, "campaigns", type_="foreignkey")
    op.drop_column("campaigns", "cover")
    # ### end Alembic commands ###
