"""update tables for state management

Revision ID: 7ab7d8ac36a9
Revises: f9aeac26c314
Create Date: 2022-10-27 23:46:20.549836

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7ab7d8ac36a9"
down_revision = "f9aeac26c314"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "campaigns",
        sa.Column("current_state", sa.String(), server_default="draft", nullable=False),
    )
    op.add_column(
        "users",
        sa.Column("access_level", sa.String(), server_default="normal", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "access_level")
    op.drop_column("campaigns", "current_state")
    # ### end Alembic commands ###
