"""add user id to updates

Revision ID: cbe0dab86311
Revises: 09dbf3ca3bd5
Create Date: 2022-12-22 23:36:46.455343

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "cbe0dab86311"
down_revision = "09dbf3ca3bd5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.add_column(
        "updates",
        sa.Column("user_id", sa.Integer(), nullable=False, server_default="0"),
    )
    op.execute(
        """
        update updates
        set user_id = (
            select distinct campaigns.campaigner_id
            from campaigns join updates
            on updates.campaign_id = campaigns.id
        );
        """
    )
    op.alter_column("updates", "user_id", server_default=None)
    op.create_foreign_key(
        None, "updates", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "updates", type_="foreignkey")
    op.drop_column("updates", "user_id")
    # ### end Alembic commands ###
